const host = "http://localhost:5050";
export const RegisterRoute=`${host}/register`;
export const LoginRoute=`${host}/login`;
export const logoutRoute=`${host}/logout`;
export const refreshTokenRoute= `${host}/refresh`;
export const adminLoginRoute=`${host}/adminlogin`
export const adminRegisterRoute=`${host}/adminregister`;
export const newEventRoute=`${host}/newevent`;
export const getEventsRoute=`${host}/getevents`;
export const getDetailsRoute=`${host}/event`;